export const OPEN_MARKUP_EDITOR = 'OPEN_MARKUP_EDITOR';
export const CLOSE_MARKUP_EDITOR = 'CLOSE_MARKUP_EDITOR';
export const SET_CURRENT_NODE_PATH = 'SET_CURRENT_NODE_PATH';
export const SAVE_TEXT = 'SAVE_TEXT';
export const MOVE_NODE = 'MOVE_NODE';
export const CLONE_NODE = 'CLONE_NODE';
export const DELETE_NODE = 'DELETE_NODE';

/* Картиночки */
export const SELECT_IMAGE = 'SELECT_IMAGE';
export const SAVE_IMAGE_EDITOR = 'SAVE_IMAGE_EDITOR';
export const CHANGE_STATE_MODEL = 'CHANGE_STATE_MODEL';
export const SAVE_MARKUP_EDITOR_STATE = 'SAVE_MARKUP_EDITOR_STATE';
export const SAVE_STATE = 'SAVE_STATE';
export const SAVE_STATE_START = 'SAVE_STATE_START';
export const SAVE_STATE_SUCCESS = 'SAVE_STATE_SUCCESS';
export const SAVE_STATE_ERROR = 'SAVE_STATE_ERROR';