export const OPEN_PAGE_SETTINGS_EDITOR  = 'OPEN_PAGE_SETTINGS_EDITOR';
export const CLOSE_PAGE_SETTINGS_EDITOR  = 'CLOSE_PAGE_SETTINGS_EDITOR';
export const SAVE_PAGE_SETTINGS = 'SAVE_PAGE_SETTINGS';


// export const FIND_NODE_BY_ID = 'FIND_NODE_BY_ID';
// export const SET_EDITOR = 'SET_EDITOR';
// export const CLOSE_EDITOR = 'CLOSE_EDITOR';
// export const SET_LINK_TEXT = 'SET_LINK_TEXT';
// export const SET_NODE_TEXT = 'SET_NODE_TEXT';
// export const SET_PAGE_EDITOR = 'SET_PAGE_EDITOR';
// export const SET_PAGE_SETTINGS = 'SET_PAGE_SETTINGS';
// export const SET_PAGE_SETTINGS_VALUE = 'SET_PAGE_SETTINGS_VALUE';
// export const SAVE_STATE_START = 'SAVE_STATE_START';
// export const SAVE_STATE_SUCCESS = 'SAVE_STATE_SUCCESS';
// export const SAVE_STATE_ERROR = 'SAVE_STATE_ERROR';
// export const GET = 'GET';
//
// /* STATUS */
// export const GET_STATUS_START = 'GET_STATUS_START';
// export const GET_STATUS_SUCCESS = 'GET_STATUS_SUCCESS';
// export const GET_STATUS_ERROR = 'GET_STATUS_ERROR';
//
// /* BACKUPS ACTIONS */
// export const GET_ALL_BACKUPS_START = 'GET_ALL_BACKUPS_START';
// export const GET_ALL_BACKUPS_SUCCESS = 'GET_ALL_BACKUPS_SUCCESS';
// export const GET_ALL_BACKUPS_ERROR = 'GET_ALL_BACKUPS_ERROR';
//
// /* TEMPLATES ACTION */
// export const GET_ALL_TEMPLATES_START = 'GET_ALL_BACKUPS_START';
// export const GET_ALL_TEMPLATES_SUCCESS = 'GET_ALL_BACKUPS_SUCCESS';
// export const GET_ALL_TEMPLATES_ERROR = 'GET_ALL_BACKUPS_ERROR';
//
// /* CREATE PAGE */
// export const CREATE_TEMPLATE_PAGE_START = 'CREATE_TEMPLATE_PAGE_START';
// export const CREATE_TEMPLATE_PAGE_SUCCESS = 'CREATE_TEMPLATE_PAGE_SUCCESS';
// export const CREATE_TEMPLATE_PAGE_ERROR = 'CREATE_TEMPLATE_PAGE_ERROR';